### ISSUE TITLE
How do you compile demo

### ISSUE THREAD

**Issue by ffbboy30** [Kucoin/kucoin-node-sdk#13]
Hi,
I'm trying to compile demo.
I've installed lodash and now I've an error "Uncaught Error: Cannot find module './config'"
I launch the level2_demo from the demo directory.
Thanks for your help

**Comment by headria** [comment]
Just rename config.tbl.js to config.js

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
