### ISSUE TITLE
getLevel2_full doesn't work

### ISSUE THREAD

**Issue by Ddystopia** [Kucoin/kucoin-node-sdk#15]
In my code:
`console.log(await API.rest.Market.OrderBook.getLevel2_full('BTC-USDT'))`
In console I see `{ code: '404', msg: 'not exist' }`

What should I do?

**Comment by ISAAC-XXYYZZ** [comment]
Due to many changes in the SDK, please refer to our latest documentation: https://www.kucoin.com/docs/beginners/introduction
Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
