### ISSUE TITLE
getAllTickers() is only returning a total of 14 tickers.

### ISSUE THREAD

**Issue by tpwatson** [Kucoin/kucoin-node-sdk#24]
I can't find any way to set the parameters to expand the ticker list size. I expected to see ALL tickers, since that is the function's name, yet its only showing 14.

**Comment by jlevers** [comment]
Are you calling the sandbox endpoint? I think the sandbox endpoint only returns a limited number of endpoints, but the main endpoint returns all the symbols: https://api.kucoin.com/api/v1/symbols

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
