### ISSUE TITLE
Several wallet address for one coin

### ISSUE THREAD

**Issue by yahya-aghdam** [Kucoin/kucoin-node-sdk#32]
Hi
Can I create several BTC wallet address to deposit and use them all in same time?

For example:
I create a BTC wallet for deposit, Then I create another wallet again. Is my first wallet still mine?

Thanks

**Comment by ISAAC-XXYYZZ** [comment]
Generally speaking, for a given coin under an account, a specific network corresponds to a single address. Our SDK is consistent with the product in this regard. However, you can create multiple sub-accounts, with each account having a different address.
