### ISSUE TITLE
applyWithdraw empty result, no action

### ISSUE THREAD

**Issue by michaelotis** [Kucoin/kucoin-node-sdk#33]
I'm attempting to use applyWithdraw on USDC to ALGO and there is no response and no record of withdrawal action

`const result = await kucoin.rest.User.Withdrawals.applyWithdraw('USDC', address, availableAmount, {chain: 'ALGO'})`

**Comment by ISAAC-XXYYZZ** [comment]
I ran this code and didn't encounter any issues. Please provide more detailed information.
Since this issue have been no updates for a long time, we will now close it. 
If you encounter any issues, feel free to provide feedback.
