### ISSUE TITLE
Api support for robots?

### ISSUE THREAD

**Issue by patriciomase** [Kucoin/kucoin-node-sdk#35]
Hey, I recently started playing with the kucoin bots, and I'd like to access the robots data via API to create some charts. (And perform actions too if that would be possible). The code would be open sourced BTW.

Is adding the robots data to the API in the plans?

Thanks.

**Comment by ISAAC-XXYYZZ** [comment]
Our latest available API can be found in this documentation: https://www.kucoin.com/docs/beginners/introduction. Currently, robots API service is not yet available, so please stay tuned.
