### ISSUE TITLE
PageSize

### ISSUE THREAD

**Issue by TransakLiquidity** [Kucoin/kucoin-node-sdk#36]
Can you add pageSize as a parameter for the endpoints that support it? Or default the API to 500. It takes to long to fetch the data if we use 50 at a time.

**Comment by FounderCasey** [comment]
bump

**Comment by TheBoroer** [comment]
seems like this is already implemented (but not documented properly?).

This fetches the first page containing 500 results for me:
![image](https://github.com/Kucoin/kucoin-node-sdk/assets/5162876/5add3636-f744-4da6-a336-07399668485e)

**Comment by ISAAC-XXYYZZ** [comment]
That's correct. For any API that requires pagination, you can pass additional pagination parameters. You can refer to the documentation for all APIs here: https://www.kucoin.com/docs/beginners/introduction
