### ISSUE TITLE
V3 API dont work

### ISSUE THREAD

**Issue by tbotteam** [Kucoin/kucoin-node-sdk#61]
node_modules\kucoin-node-sdk\src\lib\utils.js:19
  const signature = sign(timestamp + method.toUpperCase() + url + data, ApiKey.secret);
  
  TypeError: Cannot read properties of undefined (reading 'secret')

**Comment by tbotteam** [comment]
disregard

**Comment by iamalanal** [comment]
Please post your development environment information and we will investigate as soon as possible.

**Comment by ISAAC-XXYYZZ** [comment]
Since you later responded with 'disregard,' I believe this issue is resolved now. We will close it for the time being. If you encounter any issues while using it, feel free to open a new issue, and we will address it as soon as possible.
