### ISSUE TITLE
Can not install latest

### ISSUE THREAD

**Issue by ugurkriptrade** [Kucoin/kucoin-node-sdk#62]
Latest version 1.1.0 can not available for use on package managers yarn and npm

**Comment by iamalanal** [comment]
Do you have any screenshots of the error?

**Comment by ISAAC-XXYYZZ** [comment]
We released a new version(1.1.0) 21 days ago, and I just tested it without any issues. Please provide more detailed information.
https://www.npmjs.com/package/kucoin-node-sdk

**Comment by ugurkriptrade** [comment]
When i checked last time, last available version seen as 1.0.6 in package managers.
It seems fixed, can found as 1.1.0 now, thanks a lot.
