### ISSUE TITLE
Incorrect domain name in http.js (api.kucoin.io)

### ISSUE THREAD

**Issue by davidebaldini** [Kucoin/kucoin-node-sdk#8]
Excerpt of file `http.js` around row 14:

````
if (!_baseUrl) {
    _baseUrl = process.env.PRODUCTION === 'prod'
        ? 'https://api.kucoin.io'
        : 'https://openapi-sandbox.kucoin.io';
}
````

The domain name `kucoin.io` needs to be changed to `kucoin.com`, otherwise GET requests are redirected to an HTML page, causing a JSON parse error: 

````
get bullet error { FetchError: invalid json response body at https://www.kucoin.cc/api/v1/bullet-public reason: Unexpected token < in JSON at position 0
    at /home/user/pulse/node_modules/node-fetch/lib/index.js:272:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at https://www.kucoin.cc/api/v1/bullet-public reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }
````

**Comment by qhxin** [comment]
u should pass an config to API `init` function, which include `baseUrl` u use. our API production env baseUrl is `https://api.kucoin.com`.

this is the demo use: [demo/index.js](https://github.com/Kucoin/kucoin-node-sdk/blob/master/demo/index.js)
