### ISSUE TITLE
stopOrder.getOrder and stopOrder.cancelOrder currently don't work

### ISSUE THREAD

**Issue by dragonbane0** [Kucoin/kucoin-node-sdk#9]
The indicated functions return a 404 error code when used. Presumably this is due to StopOrder.js including a symbol in the delete request, while the current API documentation (https://docs.kucoin.com/#cancel-an-order-2) does not mention symbol for these request routes

**Comment by ISAAC-XXYYZZ** [comment]
Due to many changes in the SDK, please refer to our latest documentation: https://www.kucoin.com/docs/beginners/introduction
Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
